export const CHANGE_SEARCH_FIELD ='CHANGE_SEARCHFIELD';

export const REQUST_ROBOTS_PENDING ='REQUST_ROBOTS_PENDING';

export const REQUST_ROBOTS_SUCESS ='REQUST_ROBOTS_SUCESS';

export const REQUST_ROBOTS_FAILED ='REQUST_ROBOTS_FAILED';